# Generated by Django 2.1.1 on 2018-10-03 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DWH_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='user_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='searches',
            name='campaign_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DWH_app.Campaigns'),
        ),
    ]
