# Generated by Django 2.1.1 on 2018-10-05 07:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DWH_app', '0003_auto_20181003_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=1028)),
                ('is_valid', models.CharField(default='true', max_length=1024)),
                ('added_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='campaign_type',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='end',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='start',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='searches',
            name='search_key',
            field=models.CharField(max_length=1024),
        ),
        migrations.AddField(
            model_name='searchresults',
            name='search_key',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DWH_app.Searches'),
        ),
    ]
