# Generated by Django 2.1.1 on 2018-10-05 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DWH_app', '0005_auto_20181005_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresults',
            name='result',
            field=models.CharField(max_length=1028, unique=True),
        ),
        migrations.AlterField(
            model_name='searchresults',
            name='search_key',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DWH_app.Searches'),
        ),
    ]
